# generated by /home/lab/Downloads/proorigami-cde-package/cde-root/local/munk/data/phd/phd/ptgraph/ptgraph2.py -sr35 -t dssp -l crossing:black,red,green,navy,blue -b separate -q -f auto -o gradient -p none -v -g 100 -z e1af7A2 /home/lab/Downloads/1jg2.pdb
# on 12Apr2016 15:27:06
#
# 1JG2
# TRANSFERASE                             22-JUN-01   1JG2
#
load /home/lab/Downloads/1jg2.pdb
alter /1JG2, ss='L'
rebuild
alter  /1JG2//A/15-30, ss = 'H'
alter  /1JG2//A/37-45, ss = 'H'
alter  /1JG2//A/48-51, ss = 'H'
alter  /1JG2//A/54-59, ss = 'H'
alter  /1JG2//A/66-67, ss = 'S'
alter  /1JG2//A/73-74, ss = 'S'
alter  /1JG2//A/77-87, ss = 'H'
alter  /1JG2//A/95-98, ss = 'S'
alter  /1JG2//A/104-113, ss = 'H'
alter  /1JG2//A/117-121, ss = 'S'
alter  /1JG2//A/124-136, ss = 'H'
alter  /1JG2//A/142-146, ss = 'S'
alter  /1JG2//A/149-151, ss = 'H'
alter  /1JG2//A/154-156, ss = 'H'
alter  /1JG2//A/159-164, ss = 'S'
alter  /1JG2//A/173-177, ss = 'H'
alter  /1JG2//A/179-189, ss = 'S'
alter  /1JG2//A/196-204, ss = 'S'
alter  /1JG2//A/207-216, ss = 'S'
rebuild
hide everything
show cartoon
