# generated by /home/lab/Downloads/proorigami-cde-package/cde-root/local/munk/data/phd/phd/ptgraph/ptgraph2.py -sr35 -t dssp -l crossing:black,red,green,navy,blue -b separate -q -f auto -o gradient -p none -v -g 100 -z e1n4wA2 /home/lab/Downloads/e1n4wA2.pdb
# on 15Oct2015 12:47:12
#
# 1N4W
# OXIDOREDUCTASE                          01-NOV-02   1N4W
#
load /home/lab/Downloads/e1n4wA2.pdb
alter /1N4W, ss='L'
rebuild
alter  /1N4W//A/10-16, ss = 'S'
alter  /1N4W//A/20-31, ss = 'H'
alter  /1N4W//A/36-40, ss = 'S'
alter  /1N4W//A/63-65, ss = 'H'
alter  /1N4W//A/79-82, ss = 'H'
alter  /1N4W//A/83-85, ss = 'H'
alter  /1N4W//A/96-100, ss = 'S'
alter  /1N4W//A/105-109, ss = 'S'
alter  /1N4W//A/114-117, ss = 'H'
alter  /1N4W//A/128-134, ss = 'H'
alter  /1N4W//A/140-145, ss = 'H'
alter  /1N4W//A/147-155, ss = 'H'
alter  /1N4W//A/162-167, ss = 'H'
alter  /1N4W//A/169-171, ss = 'H'
alter  /1N4W//A/172-183, ss = 'H'
alter  /1N4W//A/197-204, ss = 'H'
alter  /1N4W//A/212-214, ss = 'H'
alter  /1N4W//A/232-238, ss = 'H'
alter  /1N4W//A/242-246, ss = 'S'
alter  /1N4W//A/248-255, ss = 'S'
alter  /1N4W//A/261-268, ss = 'S'
alter  /1N4W//A/274-287, ss = 'S'
alter  /1N4W//A/290-303, ss = 'H'
alter  /1N4W//A/470-472, ss = 'S'
alter  /1N4W//A/475-477, ss = 'H'
alter  /1N4W//A/487-505, ss = 'H'
rebuild
hide everything
show cartoon
